### PR TITLE
BUGFIX: Fix behaviour for fallback dimensions

### LINKED ISSUE #6: Redirect creation fails with dimension fallbacks
Given
- a setup with languages 'en' and 'de', having a fallback 'de -> 'en'
- a node existing in 'en' that is changed in 'de'

Now the check for an existing node in `createRedirectsForPublishedNode()` will never find a `$targetNode` and return early.

✅ For a deletion this is fine (for now), as a node visible via fallback cannot be deleted.
❌ For a changed `uriPathSegment` a new node is created but no redirect is set up.
❌ For a moved node a new node is indeed created, but again, no redirect is set up.

### PR DESCRIPTION
**Pull request by kdambekalns**
This is PR #11 merged into master.

Fixes #6

### CODE REVIEW

**Comment by kdambekalns** [comment]
This is the result of merging #11 into master. As there were somwe conflicts to solve, I considered it worth being pushed. Also, it is what I used to do some manual testing, since I had a Neos 3.3 project at hand.

**Comment by kdambekalns** [comment]
@dfeyer could you check again after the merge I did?

**Comment by TheLalaMan** [comment]
Any chance this can be merged soonish?

**Comment by kdambekalns** [comment]
Tested this again, works for me…

**Pull request merged**
