### PR TITLE
Remove non-rewrite url prefixes per default from redirect urls

### PR DESCRIPTION
**Pull request by sbruggmann**
Related to https://github.com/neos/redirecthandler-neosadapter/issues/23

**But** I have questions..

Who needs this $uriPathPrefix and in which situation? (https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/UriBuilder.php#L352)
Can this fallback get's removed (what I basically would do for the redirecthandler with this PR)?

### CODE REVIEW

**Comment by bwaidelich** [comment]
@dfeyer I don't know what the question is :)
But the PR looks weird to me: It should not be needed to do this low-level stuff here. Why don't you use the Neos `LinkingService`?

**Comment by dfeyer** [comment]
>  But the PR looks weird to me: It should not be needed to do this low-level stuff here. Why don't you use the Neos `LinkingService`?

@bwaidelich When you do some operation for the CLI; the routing can add the `index.php/` prefix, because it's not configured correctly.

> Who needs this $uriPathPrefix and in which situation? (https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/UriBuilder.php#L352)
> Can this fallback get's removed (what I basically would do for the redirecth

And this is the question ;) I understand that we need the fallback to support HTTP server not configured to redirected everthing to `index.php` ... but with this fallback, we need to take care of this here, as a CLI command controller will silently generate wrong URL, even if the website is correctly configured.

Maybe @sbruggmann as more details on their setup

**Comment by sbruggmann** [comment]
ah I see what I did wrong corresponding to `FLOW_REWRITEURLS`..
In case of local testing it has not to be `FLOW_REWRITEURLS=1 ./flow server:run` but `FLOW_REWRITEURLS=1 ./flow some:url-changing-command`..!

If used this way, it results in a Redirect from `./en/test-a` to `./en/test-aa`, what's not working too.
(Expected would be: `en/test-a` to `en/test-aa`.)

I will update the PR someday.

:+1: for deprecating the enc variable for the next major.

**Comment by kdambekalns** [comment]
Closing this, as the solution is to enable `FLOW_REWRITEURLS` (as is needed for any URL generation in CLI context). Feel free to re-open if you disagree. :)

**Pull request closed without merging**
